troglobit/finit

service.c
sig.c

After forking off a new child, all signals that are blocked by finit
should be unblocked before exec-ing the final binary. Also, finit now
blocks SIGHUP, so add it to the set of signals that should be
unblocked.

Unblock blocked signals after forking off a child

---

initctl.c

Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

initctl: Only show service name, not path, with plain show

---

plugins/pidfile.c
service.c
svc.h

This patch prevents too early start of services depending on other
services.  E.g, if service B depends on A then we must wait for A to
signal that it is ready before we allow B to start -- in a Finit based
system A does this by creating, or touching (updating mtime), its PID
file.  Services (like A) that support SIGHUP should call utime(), or
utimensat(), on the PID file at the end of their SIGHUP handler.
Signed-off-by: Joachim Nilsson <troglobit@gmail.com>

Assert svc condition only when PID file has been created/updated

---

api.c
exec.c
inetd.c
plugins/pidfile.c
svc.c

Signed-off-by: Joachim Nilsson <joachim.nilsson@westermo.se>

Westermo fixes for UDP inetd services and more

---

inetd.c
service.c
svc.c

This patch series is primarily for handling a bug when changing a service from inetd to regular service. The problem was that the Finit inetd socket was not closed, effectively preventing the (new) service to bind to its port.

Westermo fixes for services changing type at runtime

---

README.md
conf.c

Add support for changing the initial hard and soft resource limits for
finit and any processes it launches.
See /etc/finit.conf section in README.md for more information.

Resource limit manipulation (setrlimit)

---

conf.c

If no console is configured, then the following code gets executed:
int conf_parse_config(void)
{
...
char *fallback = FALLBACK_SHELL;
...
tty_register(fallback);
...
}
int tty_register(char *line)
{
...
cmd = strtok(line, " ");
...
}
`FALLBACK_SHELL` is constant character array and `strtok()` tries to modify the first argument, which causes a crash.

Fix SIGSEGV due to writes to const char array.

---

finit.h
helpers.c
service.c
svc.c
svc.h

Add support for registering callbacks to be called after a given
timeout.
Use this to implement forceful termination of services that refuse to
terminate upon receiving a SIGTERM. If the service PID is not collected
within 3 seconds, send a SIGKILL to it.
Also, rework restarting of crashing services. When a service crashes for
the first time, try to restart it immediately. If it crashes again, wait
a few seconds before trying again. Just as before, if it continues to
crash, block the service.

service: kill stubborn services, wait before restart

---

exec.c

Looks like array overflow checking in `run()` was broken. Condition `(i == NUM_ARGS && args[i])` right after `args[i] = NULL` was always false. I wrote some test to recheck it:
```c
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define NUM_ARGS 16
int run(char *cmd)
{
int status, result, i = 0;
char *args[NUM_ARGS + 1], *arg, *backup;
pid_t pid;
/* We must create a copy that is possible to modify. */
backup = arg = strdup(cmd);
if (!arg)
return 1; /* Failed allocating a string to be modified. */
/* Split command line into tokens of an argv[] array. */
args[i++] = strsep(&arg, "\t ");
while (arg && i < NUM_ARGS) {
/* Handle run("su -c \"dbus-daemon --system\" messagebus");
*   => "su", "-c", "\"dbus-daemon --system\"", "messagebus" */
if (*arg == '\'' || …
```

run: fix array overflow

---

conf.c
plugins/pidfile.c
service.c
service.h
svc.c
svc.h

There are some problems with applications stay in flux state/never become flux state.
* If an appliciation depend on an application run later in the service list it will be kept in flux
* When running on X86, finit sometimes complete its operation on below 1 s, the timestamp used to detect if any service is dirty is only using seconds.

Fix fluxstate

---

src/finit.c
src/finit.h

PATCH 1 + 2 is about the PATh changes discuss from PR #70 , however this solves just the 
run(/bin/foo); -> run('foo"); part.. fexist() function would need  some changes but using
stat() and friends for it would be a bit to much I guess.. 
( maybe we find a solution for that in #71 too )
However I think is not bad to have an fallback for the PATHs in case something breaks 
and having the PATH setup early is not bad too.
PATCH 3 is a Distro thing , however we really should check ifup exists before trying to use it.
Regards

Some cleanup

---

src/inetd.c

getprotobyname() returns p_proto in host endian, so it should not be
converted with ntoh. (Note: getservbyname() on the other hand does
return s_port in network endian)
Signed-off-by: Petrus Hellgren <petrus.hellgren@westermo.se>

inetd: remove ntoh on proto

---

src/helpers.h

Building finit with a uclibc-ng-toolchain fails with:
```
../src/helpers.h:53:43: error: unknown type name ‘va_list’
void    printv          (const char *fmt, va_list ap);
```

helpers.h: fix build error: unknown type name ‘va_list’

---

src/service.c

As a precaution, services who are being stopped are automatically sent
a SIGKILL after 3 seconds if they refuse to go away willingly.
Unfortunately this backup mechanism was also enabled for inetd
services which are not backed by a real process. When the service was
freed the timer was not stopped, since it was not expected to be
armed. The timer would then trigger, causing a use-after-free on the
timer watcher containing a bogus callback pointer.

Do not try to SIGKILL inetd services, they are not backed by a pid

---

src/inetd.c
src/inetd.h
src/service.c
src/svc.h

Do not restart a inetd service if the listening interface is changed. Only bring down established connection which are no longer allowed, i.e. do not touch already allowed established connections.

Only restart inetd services when neccessary

---

src/api.c
src/finit.c
src/inetd.c
src/initctl.c
src/service.c
src/svc.c
src/svc.h

Add support to specify service ID as a string.
Sample output:
```
admin@zero:~ # initctl stop udhcpc:eth1
admin@zero:~ # initctl status
3:1       running  977     [S123456789]  klogd             Kernel log daemon
9:1       running  976     [S123456789]  watchdogd         System watchdog daemon
22:eth0   running  1432    [---3-----9]  udhcpc            DHCP client (eth0)
22:eth1   stopped  0       [---3-----9]  udhcpc            DHCP client (eth1)
22:eth2   running  1452    [---3-----9]  udhcpc            DHCP client (eth2)
```

Add support to specify service ID as a string

---

src/util.c

The remaining sleep time returned by sleep is not accurate enough to be
used as a means to achieve "signal safe"-sleep. nanosleep can be used
in similar fashion instead and is granular enough for our purposes.
This issue was identified during reboot, when Finit is bombarded with
SIGCHLD, aborting the sleep that we do to give daemons a chance to shut
down gracefully. The total delay ended up being less than a second when
in fact two seconds were the intended delay.

Switch to using nanosleep in favour of sleep

---

configure.ac
contrib/fstab.bb
doc/plugins.md
plugins/Makefile.am
plugins/hotplug.c
src/conf.c
src/finit.c
src/plugin.c

This series refactors the core of Finit with the goal of giving the user more ability to tailor the system to their liking. As a result, it cuts many lines from `main()`, making it easier to get an overview of the boot process. The big stuff:
- Generic cleanup/moving around of dead/misplaced code.
- Remove all automatic mounting of different filesystems at different points in the boot process; just call out to `mount -na` and let the user decide on the exact set of filesystems and options.
- Move `udev`/`mdev` stuff out to a plugin that can be disabled and replaced with whatever the user needs (or doesn't need).
I would really like some feedback on the series as it is now, so that we can integrate these changes before going further.

[RFC] Boot refactor

---

src/sig.c

This seems to be inline with Busybox init, SysV init and, according
to the comments in code, the intended behaviour of Finit.
The effect is that `SIGPWR` will lead to Finit issuing the syscall `reboot`
with `cmd` parameter set to `RB_POWER_OFF` (rather than `RB_AUTOBOOT`), which
in turn will lead to a halt rather than a reboot.
The effect of the above inside a PID namespace other than the initial PID
namespace is that `wait` inside the parent of Finit will report that Finit was
killed with a `SIGINT` signal rather than `SIGHUP`.

Handle SIGPWR like SIGUSR2

---

src/conf.c

The tzset() function sets the global variables 'daylight', 'timezone' and 'tzname'
according to the value of the TZ environment variable, or to the value of the
_CS_TIMEZONE configuration string if TZ isn't set, or to UTC0 if neither is set.

Fix #139: System timezone changes does not 'take' in Finit

---

src/service.c

Since `logit` lives in the same process group as the service, it will receive any signal sent to that group. When a service is stopped and the process group receives `SIGTERM` (or whatever is configured) logit will stop it's business and any output from the service past this point is lost.
This PR moves `logit` outside of the service process group which means that it will live until it's `stdin` is closed, which will happens when the service has actually died.

Logit post SIGTERM, SIGINT etc.

---

src/service.c
src/svc.c
src/svc.h

Having removal status stored in the dirty status resulted in removal
status being forgotten when a service was marked as dirty, for instance
when a dependency was updated. This side effect of marke_dirty seems a bit
unexpected and instead of adding exceptions to the logic for when marking
a service dirty - let's separate the two things (dirty and removed) from each
other.
Signed-off-by: Jacques de Laval <Jacques.De.Laval@westermo.com>

Store removal status separate from dirty

---

README.md
src/service.c
src/svc.c
src/svc.h

By keeping track of when a full restart is needed, Finit can relieve
the user of having to track modifications to service configuration. This
also makes initctl reload easier to explain and reason about as the effect
of a reload should now be that any configuration updates to services will
be fully "commited" by initctl reload.

Do a full restart rather than HUP if command line of a service has changed

---

doc/TODO.md
plugins/tty.c
src/cond-w.c
src/conf.c
src/exec.c
src/finit.c
src/finit.h
src/initctl.c
src/plugin.c
src/service.c
src/sm.c
src/svc.c
src/svc.h
src/tty.c
src/tty.h

This changeset is a refactor of the tty handling to use the same backend as service/run/task/sysv configuration directives.  Not only does it reduce the overall code required, simplifying and generalizing handling of all services, but it also adds functionality like conditions for ttys.
Closes #108 #65

Tty refactor

---

src/mount.c

The iterator function getmntent() is not stable. It may skip
entries if the contents of the iterated file changes, which
is the case with /proc/mounts when filesystems are unmounted.
As a result, some filesystems were never unmounted.
To fix this, iteratation is now restarted after every
sucessful unmount.
Signed-off-by: Robert Andersson <robert.m.andersson@atlascopco.com>

Ensure all filesystems listed in /proc/mounts are unmounted

---

src/cgroup.c
src/cgroup.h
src/mount.c

"protected" is a C++ key word, replace it with "is_protected" avoid
compiling failures with C++ compiler.

Avoid using C++ key words

---

doc/conditions.md
src/mount.c
src/svc.h

There are small typos in:
- doc/conditions.md
- src/mount.c
- src/svc.h
Fixes:
- Should read `satisfied` rather than `satsifed`.
- Should read `process` rather than `prorcess`.
- Should read `measure` rather than `meausre`.
Semi-automated pull request generated by
https://github.com/timgates42/meticulous/blob/master/docs/NOTE.md

docs: Fix a few typos

---

plugins/dbus.c

Both DBUS user and pidfile is configurable in DBUS compilation, by
passing "--with-dbus-user=" and "--with-system-pid-file=", let's avoid
hard-coding them here, use macros instead.

dbus: dont hard-code daemon user/pidfile

---

src/service.c
src/svc.h

It would be good if we can control the services more specifically with
the following parameters like:
restart:N   - how many times shall the service to be restarted on
failures (<10), the default max is 10.
restart_tmo - the timeout of the restarting.
norestart   - dont restart on failures.
oncrash     - once all retrying also fail, how to deal with it,
rebooting or ignoring the failures.
Signed-off-by: Robert Andersson <robert.m.andersson@atlascopco.com>

service.c: add more parameters when starting services

---

src/cgroup.c

iwatcher of cgroup needs to be initialized earlier before any
cgroup_add functions being called.

cgroup.c: fix a iwatcher initializing issue

---

src/service.c

We like to know when a oneshot task is done, so as to start the
services that depending on it, set a oneshot condition 'done' for
that case.
Signed-off-by: Robert Andersson <robert.m.andersson@atlascopco.com>

service.c: set condition 'done' for oneshot tasks

---

src/sig.c
src/util.c
src/util.h

Instead of unconditionally waiting 2 seconds for processes to die,
check continuously for remaining processes, and break the loop when
none remain.
Turn PID 1 to a RT process with highest priority 99 during shutdown,
this ensures it would not be preempted by other RT processes.
Signed-off-by: Robert Andersson <robert.m.andersson@atlascopco.com>
Signed-off-by: Mathias Thore <mathias.thore@atlascopco.com>

Fix filesystems not unmounted at shutdown

---

src/initctl.c
src/service.c

A regression was introduced by commit f0f358a1:
[ service.c: set/clear condition 'done' for run tasks ]
svc->type is a integer but mistakenly being used as string, which will
cause crash.

service.c: fix a regression

---

test/tenv/lib.sh

In the test framework for finit, a set of shell scripts are used to
setup a test harness, run tests, and finalize tests. In the setup, a
file system is created for the virtualized/containerized environment in
which all tests are run, located at `$FINIT_SRC/test/tenv-root`. In the
tear down phase of each test, the file `/var/lock` is made readable
using `chmod +r`. It is not clear _why_ the teardown code does this, as
there are no references in the test framework to this path anywhere
else. It is conceivable that the teardown phase attempted to "reset the
state" for next test.
The code that that this commit removes does not always work. When
`/var/lock` is a symlink, and resolves to an absolute path, the test
framework does not function properly. The teardown code is run in the
context of …

Remove test code that may break tests

---

src/service.c

In commit f0f358a13:
[ service.c: set/clear condition 'done' for run tasks ]
a runtask done condition would be set/cleared when entering DONE/HALTED
states, but it did not cover all the user cases, for instance, sometimes
an end user may want to know if a runtask has finished sucessfully or
to decide what to do on its failures.
So we now change the conditions to: tsktype/tskname/success and
tsktype/tskname/failure.
And this change not only applies to run/task types, but also applies to
sysv type, in case it fails, a sysv/tskname/failure condition would be
set.

service.c: create conditions according to runtask exit status

---

src/initctl.c
src/svc.h

When a run task is started with svc->started = 1, it should be
considered started successfully so it should return 0.

initctl.c: fix a return value of run tasks

---

configure.ac
doc/plugins.md
plugins/Makefile.am
plugins/hook-scripts.c

Add a plugin that will allow the user to trigger the execution of
scripts from plugin hook points. This is particularly useful for early
boot debugging that needs to take place before regular services are
available.
For example, let's say that you want to enable some kernel tracing
before modules are loaded. With hook-scripts, you can just drop in a
shell script in /libexec/finit/hook/mount/all/ that will poke the
right control files in tracefs.

plugins: hook-scripts: new plugin for run-parts scripts on hooks

---

plugins/hotplug.c
plugins/modprobe.c

As it turns out, not all buses in Linux will add `modalias` attributes to their devices in sysfs. One notable exception are MDIO buses. The plugin's scan routine would thus not pick them up.
Fortunately, the information is always available in the device's `uevent` attribute.
Therefore, default to looking for modaliases in the device's `uevent` attribute instead, falling back to `modalias` only if `uevent` is not availble (this should never happen).

Support for coldplugging more devices

---

src/service.c

This fixes `initctl reload` correctly restarting all daemons that have new command line arguments.
Previously command line arguments changes were only acted upon if the service was explicitly reloaded using `initctl reload myservice` since it blindly sets the `svc->dirty` flag.
When checking if a service should be restarted, `svc_is_changed()` checks for the `svc->dirty` flag, and then only after that will `svc_sighup()` look for the `svc->args_dirty` flag. Hence a difference in command line arguments would not result in a service being restarted. 
https://github.com/troglobit/finit/blob/9887003b25355c94c46e05985b9738297df6f1a8/src/service.c#L2289-L2293
You could also add the `|| svc->args_dirty` check into the `svc_is_changed()`, but I think it makes sense this way.

Mark service dirty if the command line args have changed

---

src/cgroup.c
src/conf.c

It looks like the makefiles are creating a `AUTO_RELOAD` define, but the code is looking for `ENABLE_AUTO_RELOAD`. Making this change fixes the auto-reload feature for me. 
I also noticed that `conf.c do_change()` seems to ignore deleted files. 
Commenting out this checks causes a deleted or moved .conf to correctly remove a service. Not sure why this check is here so I'm afraid I might be missing some edge-cases.
```diff
static int do_change(char *dir, char *name, uint32_t mask) 
{ 
char fn[strlen(dir) + strlen(name) + 2]; 
struct conf_change *node; 
paste(fn, sizeof(fn), dir, name); 
dbg("path: %s mask: %08x", fn, mask); 
node = conf_find(fn); 
- 	if (mask & (IN_DELETE | IN_MOVED_FROM)) { 
- 		drop_change(node); 
- 		return 0; 
- 	}
if (node) {
dbg("Event already registered for %s ...", …
```

Fix AUTO_RELOAD #define typo

---

doc/config.md
src/conf.c
src/finit.c
src/finit.h
src/sig.c

Ping @JackNewman12, here's the alternative implementation of your PR, #334, making the delay optional, and possible to enable per system.

Add support for optional reboot delay

---

src/sig.c

The shutdown hooks do not have any registered callbacks. So calling `plugin_run_hooks()` ends up doing nothing.  
I think it makes sense to handle these special case hook scripts like this, but not sure if skipping some of the extra checks in `plugin_run_hooks()` makes a difference. I am guessing we don't care about the `cond_set()` and `service_step()` calls when everything has already exited.

Fix shutdown hooks not running

---

man/initctl.8
src/initctl.c

The accepted standard in Unix is to report successful executions with exitcode 0. Therefore, map a "initctl cond get" of a condition to the following exitcodes:
- On: 0
- Off: 1
- Flux: 255
Fixes: c3c662fe6446 ("initctl: ensure 'cond get' support flux state")
Signed-off-by: Tobias Waldekranz <tobias@waldekranz.com>

initctl: Follow priciple of least surprise for "cond get"

---

src/service.c

When debug is disabled an empty string `""` is sent as an arg to the logger process specified with `log`, both `logit` and `logger` interpret this as a log message and exit after emitting a single message containing the following parameters.

Fix log child exiting with debug disabled

---

plugins/modprobe.c
src/conf.c
src/mdadm.c
src/plugin.c
src/tmpfiles.c
src/util.c
src/util.h

This PR fixes #389.
Tested on a glibc and musl system.
- Implemented a custom `basename()` version: `basenm()` using the simple implementation of it that was present in `maybe_fopen_alias()`
- Modified the simple implementation of it to return a copy of the argument that was given, instead of `NULL` if no `/` was present
- Changed all calls to `basename()` to our custom version
- Changed the comparison in `maybe_fopen_alias()` as we no longer return `NULL`

Fix compilation on musl by implementing a custom basename

---

configure.ac
src/cgroup.c

We would like cgroup2 to be configurable at build time, when it's disabled, finit will not check /sys/fs/cgroup for cgroup2 support.
The reason for why we need this is because we'd like to use our own rules for controlling cgroup2, and it's hard to adapt to finit's default settings.

configure.ac: make cgroup2 configurable

---

src/finit.c
src/util.c
src/util.h

This is a patch for finit 4.8 beta 1.
It adds the function fistmpfs to determine if a new tmpfs mount should be performed on /run and /tmp. The function supports cases where more complex mount hierarchies are in use, including overlayfs backed mounts.
In our system, /tmp is a symbolic link to a subdirectory in an overlayfs mount. This means that /tmp does not explicitly show up in /proc/mounts, so in fs_finalize, finit decides to mount a new tmpfs on top of it.
This turns out to be problematic for our smallest systems where the new tmpfs on /tmp is not large enough.
I do realize this may be a bit particular to our specific setup, but the patch works on our system. Any comments are welcome.

Avoid remounting already mounted /run and /tmp directories

---

src/tmpfiles.c

When dealing with "L+" and "R", the function call 'nftw' should not follow symbolic links, otherwise, it would also delete the targets which is wrong.
For instance, if there is already a symbolic link:
```
/path/to/the/link -> /path/to/some/folder
```
if we set the following in a tmpfile conf:
```
L+ /path/to/the/link -    -    -     - /path/to/the/target
```
the result would be /path/to/some/folder also get deleted, which it should not.
it could be even worse, when the symbolic link already is pointing to: /path/to/the/target, the whole /path/to/the/target would be deleted on next system boot.

tmpfiles.c: prevent nftw follow symbolic links

---

src/finit.c

fix for #421: add support for 'nofail' fstab option. if present, finit's fsck invocation ignores errors for this device.
this is useful if you have an fstab entry for a device with UUID= or LABEL= which isn't always present and which you'd like to not  bail on (so you set nofail). in this case finit leaves the presence-or-not decision to fsck, which exits nonzero.
for block devices that are directly listed in fstab this change isn't important, because for such finit looks for the blockdev's existence and skips the fsck if n/a.

fstab with UUID/LABEL: nofail handling for fsck

---

src/helpers.c

i wanted to play around with `finit` a little bit so i launched it as pid1 in a `systemd-nspawn` container - i noticed that the `container` condition wasn't met
before patch:
```
$ initctl cond dump | grep container
```
after patch:
```
$ initctl cond dump | grep container
1    init                on      <int/container>
```
may or may not be useful to others, thought i would submit in case - thank you

add systemd-nspawn to the list of container types

---

plugins/procps.c

my `sysctl` isn't located in `/sbin` - i followed convention seen elsewhere

allow sysctl path to be configured at build time

---

src/service.c

citing https://skarnet.org/software/s6/notifywhenup.html
> - When your daemon is ready, write a newline to this file descriptor.
>   - If you like, you may write other data before the newline, just in case it is printed to the terminal. It is not necessary, and it is best to keep that data short. If the line is read by [s6-supervise](https://skarnet.org/software/s6/s6-supervise.html), it will be entirely ignored; only the newline is important.
while testing out [eudev support for s6 style readiness notifications](https://github.com/eudev-project/eudev/pull/290) i found out that `finit` is a bit too strict in its implementation
this patch relaxes `finit` check so it better implements the spec

improve notify:s6 compatibility

---

src/service.c

https://github.com/troglobit/finit/blob/2760616c73af1284bd71ae9aa8226c3da3ff8544/src/service.c#L1420
`prev` and `svc->args[...]` are compared but `prev` has less bytes available than `svc->args[...]` does, which can result in truncated data being compared to determine if a service is dirty
for example:
```
service [234] name:mariadb restart:10 @mariadb:mariadb <!service/syslogd/ready,task/mariadb-init/success> notify:systemd log /nix/store/z5lmh4g28xxbdjc6zsblajw91fnmjd8d-mariadb-server-10.11.13/bin/mysqld --defaults-file=/etc/my.cnf --user=mariadb --datadir=/var/lib/mariadb --basedir=/nix/store/z5lmh4g28xxbdjc6zsblajw91fnmjd8d-mariadb-server-10.11.13 -- mariadb database service
```
this results in `finit` marking some of my services as dirty every time i run `initctl reload`
by giving …

service.c/parse_cmdline_args: handle loooooong arguments
